'use server';

import { insertLead, LeadData } from '@/lib/supabase';

const RESEND_API_KEY = process.env.RESEND_API_KEY || '';
const NOTIFICATION_EMAIL = process.env.NOTIFICATION_EMAIL || 'salman@scewwood.in';

export interface SubmitLeadState {
  success: boolean;
  message?: string;
  error?: string;
}

/**
 * Server Action for handling customer lead submissions.
 */
export async function submitLeadAction(data: {
  name: string;
  phone: string;
  email?: string;
  message?: string;
  sourcePage?: string;
}): Promise<SubmitLeadState> {
  const name = data.name?.trim();
  const phone = data.phone?.trim();
  const email = data.email?.trim();
  const message = data.message?.trim();
  const sourcePage = data.sourcePage || 'Contact Page';

  // Basic validation
  if (!name || !phone) {
    return {
      success: false,
      error: 'Name and phone number are required.',
    };
  }

  const leadPayload: LeadData = {
    name,
    phone,
    email: email || undefined,
    message: message || undefined,
    source_page: sourcePage,
  };

  // 1. Insert lead into Supabase
  const dbResult = await insertLead(leadPayload);
  if (!dbResult.success) {
    console.error('[Lead Action Error] DB insertion failed:', dbResult.error);
    // Proceed to send email notification anyway so no lead is lost!
  }

  // 2. Send instant email alert via Resend API
  if (RESEND_API_KEY) {
    try {
      const emailRes = await fetch('https://api.resend.com/emails', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${RESEND_API_KEY}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          from: 'One Studio Leads <leads@onestudio.in>',
          to: [NOTIFICATION_EMAIL],
          subject: `🚨 New Lead Received: ${name} (${phone})`,
          html: `
            <div style="font-family: Arial, sans-serif; padding: 20px; color: #333;">
              <h2 style="color: #f2bd19; background-color: #0f172a; padding: 12px 16px; border-radius: 8px;">
                New Inquiry Received from ${sourcePage}
              </h2>
              <table style="width: 100%; border-collapse: collapse; margin-top: 16px;">
                <tr><td style="padding: 8px; font-weight: bold; border-bottom: 1px solid #ddd;">Name:</td><td style="padding: 8px; border-bottom: 1px solid #ddd;">${name}</td></tr>
                <tr><td style="padding: 8px; font-weight: bold; border-bottom: 1px solid #ddd;">Phone:</td><td style="padding: 8px; border-bottom: 1px solid #ddd;"><a href="tel:${phone}">${phone}</a></td></tr>
                <tr><td style="padding: 8px; font-weight: bold; border-bottom: 1px solid #ddd;">Email:</td><td style="padding: 8px; border-bottom: 1px solid #ddd;">${email || 'N/A'}</td></tr>
                <tr><td style="padding: 8px; font-weight: bold; border-bottom: 1px solid #ddd;">Source Page:</td><td style="padding: 8px; border-bottom: 1px solid #ddd;">${sourcePage}</td></tr>
                <tr><td style="padding: 8px; font-weight: bold; border-bottom: 1px solid #ddd;">Message:</td><td style="padding: 8px; border-bottom: 1px solid #ddd;">${message || 'No additional message.'}</td></tr>
              </table>
              <p style="margin-top: 20px; font-size: 12px; color: #666;">This notification was auto-generated by your Next.js Server Action backend.</p>
            </div>
          `,
        }),
      });

      if (!emailRes.ok) {
        const errText = await emailRes.text();
        console.error('[Resend Email Error]', errText);
      }
    } catch (emailErr) {
      console.error('[Resend Email Exception]', emailErr);
    }
  } else {
    console.log('[Lead Server Action] RESEND_API_KEY missing. Lead logged to server console:', leadPayload);
  }

  return {
    success: true,
    message: 'Thank you! Your details have been submitted successfully. Our team will contact you shortly.',
  };
}
